### ISSUE TITLE
GET /3 always throws error

### ISSUE THREAD

**Issue by dheenaINDIAN** [zackehh/cachex#113]
```
Cachex.get(:my_cache, "/api/v1/packages", fn(_key, db_conn) ->
  Database.load_packages(db_conn)
end)
```
The above code gives error as,
`no function clause matching in Cachex.get/3`

**Comment by zackehh** [comment]
@dheenaINDIAN did you set up a state for your fallbacks? If not, then you'll only require a single argument in the function handler.
