### ISSUE TITLE
Can't replicate data to another node

### ISSUE THREAD

**Issue by Sotorin** [zackehh/cachex#25]
Can I replicate data across two connected nodes? I created simple elixir project to play with the cache and then started two elixir nodes in separate IEX sessions. I connected the nodes, `start_link`'ed both of them, called the `Cachex.add_node(...)` and I can only see cached values which were stored on their respective nodes. "key"'s value is not visible from node 'two' and "key2"'s value is not visible from node 'one'. Screen captures of these sessions attached for your reference. What could be the issue? 

<img width="660" alt="screen shot 2016-04-27 at 6 12 10 pm" src="https://cloud.githubusercontent.com/assets/1545379/14871035/685e67ca-0ca4-11e6-87b9-985482e26226.png">
<img width="660" alt="screen shot 2016-04-27 at 6 12 26 pm" src="https://cloud.githubusercontent.com/assets/1545379/14871040/7800c574-0ca4-11e6-9874-e9c0b3501180.png">

**Comment by zackehh** [comment]
@Sotorin I believe the problem is that your first call needs to declare a `nodes` key rather than what you're currently using. All nodes should really declare all nodes they expect to talk to.

So in terminal one:

```
Cachex.start_link([ name: :my_cache, nodes: [ :one@Artur, :two@Artur ] ])
```

And in terminal two:

```
Cachex.start_link([ name: :my_cache, nodes: [ :one@Artur, :two@Artur ] ])
```

Please can you see if this works?

**Comment by Sotorin** [comment]
@zackehh - Yeah, this worked like a charm! Thank you very much! I was only running it from IEx as part of getting familiar with the library. Ultimately it will be used in a Phoenix app, which will be deployed in distributed environment with intent of having users share the cache regardless of which node they actually connect to. Multi-Layered caching will be the next feature I'll experiment with, looks really cool.

I was using `Cachex.add_node/2` because I couldn't connect it using `Cachex.start_link` and thus my original post. I'll use the same config settings in my Phoenix app and try testing in distributed setup. Normally I have to connect the nodes for Phoenix Pub/Sub to work but if Cachex will do it for me then there will be one less thing to worry about. Thanks again, great job!



<img width="668" alt="screen shot 2016-04-27 at 7 34 42 pm" src="https://cloud.githubusercontent.com/assets/1545379/14872181/73b0d7ec-0caf-11e6-8b69-9d80b53f1066.png">
<img width="663" alt="screen shot 2016-04-27 at 7 34 58 pm" src="https://cloud.githubusercontent.com/assets/1545379/14872297/7cecfeac-0cb0-11e6-92f1-191bae263b85.png">

**Comment by zackehh** [comment]
@Sotorin glad to help :) Adding a node is a very manual way to go about it - such as if you ssh into the remote console on the node because you have a new physical node to add. Usually you'll just want to define them up front - even if they don't exist yet, it'll connect properly when they spin up.

**Comment by zackehh** [comment]
For what it's worth, I added a commit 8660da1 which will add a bit more info if you try and replicate using `add_node/2` and it doesn't work.
