### ISSUE TITLE
Example in the README wrong

### ISSUE THREAD

**Issue by philipgiuliani** [zackehh/cachex#34]
The example in the README does not work:
```elixir
{ :ok, information } = Cachex.get(:info_cache, "/api/v1/packages", fallback: fn(key, db) ->
  Database.query_all_packages(db)
end)
```

The problem is that the first time, Cachex returns `{ :loaded, information }`, and so it crashes because it doesn't match.

It could be changed to either `{ status, information }` or `information = Cachex.get!(...)`

Its very hard to match a successful status when there is `:ok` and `:loaded ` both successful...

**Comment by zackehh** [comment]
@philipgiuliani The `:loaded` key is used to determine how frequently you're hitting your backend rather than the cache, so it's useful for metrics.

I'll take care of that example for you (although it won't be pushed to zackehh.github.io/cachex until next release).
