### ISSUE TITLE
Enum.group_by/3 with a map/dictionary as second element is deprecated

### ISSUE THREAD

**Issue by philipgiuliani** [zackehh/cachex#47]
Just upgraded to Elixir 1.3.0

```
warning: Enum.group_by/3 with a map/dictionary as second element is deprecated, please use a map instead
  (elixir) lib/enum.ex:1000: Enum.group_by/3
  (cachex) lib/cachex/hook.ex:68: Cachex.Hook.hooks_by_type/2
  (cachex) lib/cachex/options.ex:94: Cachex.Options.setup_hooks/2
  (cachex) lib/cachex/options.ex:44: Cachex.Options.parse/1
  (cachex) lib/cachex.ex:1050: Cachex.parse_options/1
```

Line: https://github.com/zackehh/cachex/blob/master/lib/cachex/hook.ex#L62

**Comment by zackehh** [comment]
Already about to fix when #46 is merged. Just working on coverage.

**Comment by philipgiuliani** [comment]
Oh god sorry, haven't looked at the PR. Awesome work and thank you! You close it when its merged?

**Comment by zackehh** [comment]
@philipgiuliani no problem :) I'm currently going through my libs and updating for v1.3.

Yeah, this issue will be closed when that PR is merged (soon).
